repos:
- repo: local
  hooks:
    - id: deno-fmt
      name: deno fmt
      entry: deno fmt
      language: system
      types: [file]
      files: '\.ts$'
    - id: deno-lint
      name: deno lint
      entry: deno lint --unstable
      language: system
      types: [file, ts]
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.15.3
  hooks:
    - id: commitizen
      stages: [commit-msg]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: check-json
    - id: check-symlinks
    - id: check-toml
    - id: check-yaml
